# Generated by Django 5.2.4 on 2025-07-31 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('version', models.CharField(choices=[('V1', 'Version 1'), ('V2', 'Version 2')], max_length=2)),
                ('complexity', models.CharField(choices=[('simple', 'Simple'), ('medium', 'Medium'), ('complex', 'Complex')], max_length=10)),
                ('is_managed_by', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
