# Generated by Django 5.2.4 on 2025-07-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsExtractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_value', models.CharField(choices=[('V1', 'Version 1'), ('V2', 'Version 2')], max_length=2)),
                ('repo_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported', models.BooleanField(default=False)),
            ],
        ),
    ]
