# Generated by Django 5.2.4 on 2025-07-31 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0002_tagsextractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tags_extractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='tag_manager_component.tagsextractor'),
        ),
        migrations.AddField(
            model_name='tag',
            name='theme_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
