# Generated by Django 5.2.4 on 2025-07-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0003_tag_tags_extractor_tag_theme_type_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsextractor',
            name='start_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tagsextractor',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
    ]
