# Generated by Django 5.2.4 on 2025-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0004_tagsextractor_start_page_tagsextractor_total_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsextractor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
