# Generated by Django 5.2.4 on 2025-07-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0005_tagsextractor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1_component_name', models.CharField(max_length=100)),
                ('v2_component_name', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='tagsextractor',
            name='repo_url',
            field=models.URLField(unique=True),
        ),
    ]
