# Generated by Django 5.2.4 on 2025-08-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0006_tagmapper_alter_tagsextractor_repo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'theme_type')},
        ),
    ]
