# Generated by Django 5.2.4 on 2025-08-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0007_alter_tag_name_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'theme_type', 'version')},
        ),
    ]
