# Generated by Django 5.2.4 on 2025-08-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0008_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='theme_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
