# Generated by Django 5.2.4 on 2025-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0009_alter_tag_theme_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmapper',
            name='v1_component_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tagmapper',
            name='v2_component_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tagmapper',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
