# Generated by Django 5.2.4 on 2025-08-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0011_complexityparameter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='complexityparameter',
            name='single_complexity_config',
        ),
    ]
