# Generated by Django 5.2.4 on 2025-08-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0011_complexityparameter'),
    ]

    operations = [
        # No-op migration since constraint was never created in 0011
    ]
