# Generated by Django 5.2.4 on 2025-08-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0014_add_complexity_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complexityparameter',
            unique_together={('complexity_type',)},
        ),
    ]
