# Generated by Django 5.2.4 on 2025-08-13 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0015_alter_complexityparameter_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmapper',
            name='category',
            field=models.CharField(choices=[('layout', 'Layout Component'), ('form', 'Form Component'), ('media', 'Media Component'), ('interactive', 'Interactive Element'), ('ui', 'UI Component'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='tagmapper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagmapper',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mappers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagmapper',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this mapping'),
        ),
        migrations.AddField(
            model_name='tagmapper',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tagmapper',
            name='mapping_rules',
            field=models.JSONField(blank=True, help_text='JSON mapping rules for transformation', null=True),
        ),
        migrations.AddField(
            model_name='tagmapper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
