# Generated by Django 5.2.4 on 2025-08-13 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0016_tagmapper_category_tagmapper_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmapper',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tagmapper',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
