# Generated by Django 5.2.4 on 2025-08-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0017_alter_tagmapper_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='used_in_website',
            field=models.IntegerField(default=0, help_text='Number of websites using this component'),
        ),
        migrations.AddField(
            model_name='tagmapper',
            name='used_in_website',
            field=models.IntegerField(default=0, help_text='Number of websites using this mapping'),
        ),
    ]
