# Generated by Django 5.2.4 on 2025-08-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0018_add_used_in_website_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsextractor',
            name='extraction_method',
            field=models.CharField(choices=[('GITREPO', 'GitHub API Repository'), ('CLONE', 'Local Repository Clone')], default='GITREPO', max_length=10),
        ),
    ]
