# Generated by Django 5.2.4 on 2025-08-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0019_tagsextractor_extraction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsextractor',
            name='extraction_method',
            field=models.CharField(choices=[('GITAPI', 'GitHub API Repository'), ('CLONE', 'Local Repository Clone')], default='GITAPI', max_length=10),
        ),
    ]
