# Generated by Django 5.2.4 on 2025-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0020_alter_tagsextractor_extraction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmapper',
            name='v1_component_attributes',
            field=models.TextField(blank=True, help_text='Attributes for V1 tag', null=True),
        ),
        migrations.AddField(
            model_name='tagmapper',
            name='v1_tag_attributes',
            field=models.TextField(blank=True, help_text='LongText: Raw attributes for V1 tag'),
        ),
        migrations.AddField(
            model_name='tagmapper',
            name='v2_component_attributes',
            field=models.TextField(blank=True, help_text='Attributes for V2 tag', null=True),
        ),
        migrations.AddField(
            model_name='tagmapper',
            name='v2_tag_attributes',
            field=models.TextField(blank=True, help_text='LongText: Raw attributes for V2 tag'),
        ),
    ]
