# Generated by Django 5.2.4 on 2025-09-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_manager_component', '0021_tagmapper_v1_component_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmapper',
            name='v1_tag_attributes',
        ),
        migrations.RemoveField(
            model_name='tagmapper',
            name='v2_tag_attributes',
        ),
    ]
