from django.urls import path
from . import views

urlpatterns = [
    path('', views.site_list, name='site_list'),
    path('create/', views.site_create, name='site_create'),
    path('<int:pk>/edit/', views.site_edit, name='site_edit'),
    path('<int:pk>/delete/', views.site_delete, name='site_delete'),
    path('<int:site_id>/meta/', views.site_meta_list, name='site_meta_list'),
    path('<int:site_id>/meta/create/', views.site_meta_create, name='site_meta_create'),
    path('<int:site_id>/meta/<int:pk>/edit/', views.site_meta_edit, name='site_meta_edit'),
    path('<int:site_id>/meta/<int:pk>/delete/', views.site_meta_delete, name='site_meta_delete'),
    path('<int:site_id>/analyze/', views.analyze_sitemap, name='analyze_sitemap'),
    path('import-websites-csv/', views.import_websites_csv, name='import_websites_csv'),
    path('batch-analyze-sitemaps/', views.batch_analyze_sitemaps, name='batch_analyze_sitemaps'),
    path('batch-analysis-progress/', views.batch_analysis_progress, name='batch_analysis_progress'),
    path('batch-update-complexity/', views.batch_update_complexity, name='batch_update_complexity'),
    path('batch-complexity-progress/', views.batch_complexity_progress, name='batch_complexity_progress'),
    path('download-sites-import-template/', views.download_sites_import_template, name='download_sites_import_template'),
    path('export-sites-csv/', views.export_sites_csv, name='export_sites_csv'),
    path('cleanup-site-data/', views.cleanup_site_data, name='cleanup_site_data'),
    path('<int:site_id>/meta/create-webbuilder/', views.trigger_webbuilder_site_creation, name='trigger_webbuilder_site_creation'),
    path('<int:site_id>/meta/run-import-script/', views.run_import_script, name='run_import_script'),
    path('<int:site_id>/meta/run-export-script/', views.run_export_script, name='run_export_script'),
    path('<int:site_id>/meta/export/', views.export_meta_page, name='export_meta_page'),
    path('<int:site_id>/meta/export/start/', views.export_site_meta, name='export_site_meta'),
    path('<int:site_id>/meta/file-upload/', views.file_upload_meta, name='file_upload_meta'),
    path('<int:site_id>/meta/file-upload/status/', views.check_file_upload_status, name='check_file_upload_status'),
    path('<int:site_id>/meta/file-upload/clear-status/', views.clear_file_upload_status, name='clear_file_upload_status'),
    path('<int:site_id>/meta/import/', views.import_site_meta, name='import_site_meta'),
    path('<int:site_id>/meta/check-export-status/', views.check_export_status, name='check_export_status'),
    path('<int:site_id>/meta/download-export/', views.download_exported_meta, name='download_exported_meta'),
    path('<int:site_id>/meta/cancel-export/', views.cancel_export, name='cancel_export'),
    path('<int:site_id>/meta/check-import-status/', views.check_import_status, name='check_import_status'),
    path('<int:site_id>/block/import/', views.import_block, name='import_block'),
    path('<int:site_id>/file-attribute/import/', views.import_file_attribute, name='import_file_attribute'),
    path('<int:site_id>/file/import/', views.import_file, name='import_file'),
    path('<int:site_id>/meta/export/status/', views.export_status, name='export_status'),
    path('<int:site_id>/pages/import/', views.pages_import_view, name='pages_import'),
    path('<int:site_id>/pages/import/<str:action>/', views.pages_import_action, name='pages_import_action'),
    path('<int:site_id>/pages/import/<str:action>/status/', views.pages_import_action_status, name='pages_import_action_status'),
    path('<int:site_id>/pages/import/<str:action>/clear-status/', views.clear_pages_import_action_status, name='clear_pages_import_action_status'),
]
