# Generated by Django 5.2.4 on 2025-08-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_manager', '0004_remove_sitelistdetails_custom_component_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMigrationUtility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1_body', models.TextField(blank=True, null=True)),
                ('v1_css', models.TextField(blank=True, null=True)),
                ('v1_js', models.TextField(blank=True, null=True)),
                ('v2_body', models.TextField(blank=True, null=True)),
                ('v2_css', models.TextField(blank=True, null=True)),
                ('v2_js', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
