# Generated by Django 5.2.4 on 2025-08-06 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration_utility', '0003_remove_site_meta_details_id_sql'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamigrationutility',
            options={'ordering': ['-created_at'], 'verbose_name': 'Data Migration', 'verbose_name_plural': 'Data Migrations'},
        ),
        migrations.AddField(
            model_name='datamigrationutility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamigrationutility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
