# Generated by Django 5.2.4 on 2025-09-16 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration_utility', '0004_alter_datamigrationutility_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for this knowledge base entry', max_length=200)),
                ('component_name', models.CharField(help_text='Name of the component (e.g., helix-image, helix-accordion)', max_length=100)),
                ('v1_code', models.TextField(help_text='V1 version of the component code')),
                ('v2_code', models.TextField(help_text='V2 version of the component code')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this migration pattern')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this entry is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
