# Generated by Django 5.2.4 on 2026-04-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration_utility', '0004_alter_datamigrationutility_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteListDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webbuilder_site_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
