# Generated by Django 5.2.4 on 2025-08-04 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteListDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(unique=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('helix_v1_component', models.TextField(blank=True, null=True)),
                ('helix_v2_compatible_component', models.TextField(blank=True, null=True)),
                ('helix_v2_non_compatible_component', models.TextField(blank=True, null=True)),
                ('v2_compatible_count', models.IntegerField(default=0)),
                ('v2_non_compatible_count', models.IntegerField(default=0)),
                ('custom_component', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteMetaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('helix_v1_component', models.TextField(blank=True, null=True)),
                ('helix_v2_compatible_component', models.TextField(blank=True, null=True)),
                ('helix_v2_non_compatible_component', models.TextField(blank=True, null=True)),
                ('v2_compatible_count', models.IntegerField(default=0)),
                ('v2_non_compatible_count', models.IntegerField(default=0)),
                ('custom_component', models.TextField(blank=True, null=True)),
                ('custom_component_count', models.IntegerField(default=0)),
                ('site_list_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_details', to='site_manager.SiteListDetails')),
            ],
        ),
    ]
