# Generated by Django 5.2.4 on 2025-08-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemetadetails',
            name='custom_component_count',
            field=models.IntegerField(default=0),
        ),
    ]
