# Generated by Django 5.2.4 on 2025-08-05 07:25

from django.db import migrations, connection



def add_custom_component_count(apps, schema_editor):
    table_name = 'site_manager_sitemetadetails'
    column_name = 'custom_component_count'
    with connection.cursor() as cursor:
        cursor.execute(f"SHOW COLUMNS FROM {table_name} LIKE '{column_name}'")
        result = cursor.fetchone()
        if not result:
            cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} int DEFAULT 0")

class Migration(migrations.Migration):
    dependencies = [
        ('site_manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_custom_component_count),
    ]
