# Generated by Django 5.2.4 on 2025-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0002_sitemetadetails_custom_component_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelistdetails',
            name='custom_component_count',
            field=models.IntegerField(default=0),
        ),
    ]
