# Generated by Django 5.2.4 on 2025-08-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0003_sitelistdetails_custom_component_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitelistdetails',
            name='custom_component_count',
        ),
    ]
