# Generated by Django 5.2.4 on 2025-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0004_remove_sitelistdetails_custom_component_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelistdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitemetadetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
