# Generated by Django 5.2.4 on 2025-08-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0005_alter_sitelistdetails_id_alter_sitemetadetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelistdetails',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
