# Generated by Django 5.2.4 on 2025-08-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0006_sitelistdetails_is_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelistdetails',
            name='complexity',
            field=models.CharField(choices=[('simple', 'Simple'), ('medium', 'Medium'), ('complex', 'Complex')], default='medium', help_text='Site complexity classification (simple, medium, complex)', max_length=10),
        ),
    ]
