# Generated by Django 5.2.4 on 2025-08-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0007_sitelistdetails_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelistdetails',
            name='complexity_configuration',
            field=models.TextField(blank=True, help_text='JSON configuration data used to determine the complexity of this site', null=True),
        ),
    ]
