# Generated by Django 5.2.4 on 2025-08-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0008_sitelistdetails_complexity_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelistdetails',
            name='last_analyzed',
            field=models.DateTimeField(blank=True, help_text='Date and time when the site was last analyzed', null=True),
        ),
    ]
