# Generated by Django 5.2.4 on 2025-09-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0009_sitelistdetails_last_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelistdetails',
            name='webbuilder_site_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
