# Generated by Django 5.2.4 on 2025-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0009_sitelistdetails_last_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelistdetails',
            name='helix_site_id',
            field=models.IntegerField(default=0),
        ),
    ]
