# Generated by Django 5.2.4 on 2026-04-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0010_sitelistdetails_webbuilder_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelistdetails',
            name='webbuilder_site_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
